version: '3.2'

services:
  powershell-work:
    build:
      context: .
      dockerfile: Dockerfile.powershell-work
    container_name: ps-work
    image: powershell
    volumes:
    - /dev/pts:/dev/pts
    - /workspace/mowgli/mowgli:/workspace/mowgli
    - /workspace/mowgli/mowgli-build:/workspace/mowgli-build
    - /workspace/mowgli/mowgli-modules:/workspace/mowgli-modules
    - /workspace/mowgli/mowgli-modules-build:/workspace/mowgli-modules-build
    - ~/workspace/windows-coverity:/home/fgth/workspace/windows-coverity
    - /opt/coverity:/opt/coverity
    - /dev/shm:/dev/shm
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /etc/localtime:/etc/localtime:ro
    devices:
    - /dev/dri:/dev/dri
    privileged: true
    stdin_open: true
    tty: true
    user: fgth
    dns: 10.160.64.32
    hostname: powershell

  powershell-home:
    build:
      context: .
      dockerfile: Dockerfile.powershell
    container_name: ps-home
    image: powershell
    volumes:
    - /dev/pts:/dev/pts
    - ~/workspace:/home/fgth/workspace
    - /dev/shm:/dev/shm
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /etc/localtime:/etc/localtime:ro
    environment:
    - DISPLAY=unix:0
    privileged: true
    stdin_open: true
    tty: true
    user: fgth
    hostname: powershell
